### ISSUE TITLE
Withdraw - "25: Signature error."

### ISSUE THREAD

**Issue by tulasacra** [JKorf/CoinEx.Net#24]
im getting an error on Withdraw - "25: Signature error."
maybe transfer_method parameter missing? https://github.com/coinexcom/coinex_exchange_api/wiki/062submit_withdraw

**Comment by JKorf** [comment]
I've added the parameter, let me know if you still have issues

**Comment by tulasacra** [comment]
unfortunately im still getting the same error. Is it possible to easily check what is the request being sent?

**Comment by JKorf** [comment]
Yes, you can turn on Debug logging by setting LogVerbosity = LogVerbosity.Debug in the client settings. It will then output the request and response.

**Comment by tulasacra** [comment]
we have a typo
 "tranfer_method":"local"}

**Comment by JKorf** [comment]
Ah. I've fixed that in the latest version.

**Comment by tulasacra** [comment]
updated, but still the same error.
i found this, which makes me think maybe the values need to be "1"/"2"
https://github.com/ccxt/ccxt/commit/a0e0728cb6f0687e293cbd83948bc919eb85feba

**Comment by JKorf** [comment]
Good find, I've adjusted it in the latest beta release

**Comment by trsv** [comment]
Hello. 
I also get Signature error, but only when an address has MEMO.
Without memo everything works well.
Could you help me, please, with that?
My source code (C++/Qt)
```
QByteArray CoinExManager::generateSign(const QUrlQuery &query) const
{
    return generateSign(query, m_api_secret.toUtf8());
}

QByteArray CoinExManager::generateSign(const QUrlQuery &query, const QByteArray &secret)
{
    const auto querySorted = HttpUtils::sortUrlQuery2String(query)
            .append("&secret_key=")
            .append(secret)
            .toUtf8();

    // generate sign md5
    return QCryptographicHash::hash(querySorted, QCryptographicHash::Md5).toHex().toUpper();
}



Birga::WithdrawnedOrder CoinExManager::withdraw(const QString &coin, const QString &amount,
                                                  const QString &address, const QString &network,
                                                  const QString &memo) const
{
    static const auto endpoint = "/v1/balance/coin/withdraw";

    QJsonObject query;
    query["access_id"] = m_api_key;
    query["coin_type"] = coin; // coin

    if (!network.isEmpty()) {
        query["smart_contract_name"] = network;
    }

    // append memo if not empty
    auto addressFinal = address;
    if (!memo.isEmpty()) {
        addressFinal += ":" + memo;
    }

    query["coin_address"] = addressFinal;
    query["transfer_method"] = "onchain";
    query["actual_amount"] = amount;
    query["tonce"] = QString::number(QDateTime::currentMSecsSinceEpoch());

    const auto dataPost = QJsonDocument(query).toJson(QJsonDocument::Compact);
    const auto response = std::get<1>(sendAuthRequest(TIMEOUT_CREATE, "POST", endpoint,
                                                      QUrlQuery(), dataPost));

    DataIO::makeLog("withdraw:" + response, "log_coinex.txt");

    const auto json = QJsonDocument::fromJson(response).object();
    const auto code = json["code"].toInt();
    const auto msg = json["message"].toString();
    const auto data = json["data"].toObject();
    return {QString::number(data["coin_withdraw_id"].toInt()), code == 0, msg};
}



std::tuple<bool, QByteArray> CoinExManager::sendAuthRequest(const int &timeout,
                                                            const QByteArray &method,
                                                            const QString &endpoint,
                                                            const QUrlQuery &query,
                                                            const QByteArray &data) const
{
    // sort params in query string
    const auto dataJson = QJsonDocument::fromJson(data).object();
    const auto list = dataJson.toVariantHash();
    QUrlQuery t;
    for (auto it = list.begin(); it != list.end(); ++it) {
        t.addQueryItem(it.key(), it.value().toString());
    }

    QUrl url;
    url.setUrl("https://api.coinex.com");
    url.setPath(endpoint);
    url.setQuery(query);

    QNetworkRequest request;
    request.setRawHeader("Content-Type", "application/json");
    request.setRawHeader("User-Agent", "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) " \
                         "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36");
    request.setRawHeader("authorization", generateSign((query.isEmpty()) ? t : query));
    request.setUrl(url);

    return httpRequest(timeout, method, request, data);
}
```
Thank you kindly.

**Comment by tulasacra** [comment]
same error, same typo in beta 8

,"tranfer_method":"1"}

**Comment by JKorf** [comment]
I see, I fixed one issue in the master branch and the other in the beta branch.. I've fixed the typo in the beta release and pushed a new version.

**Comment by tulasacra** [comment]
still no luck 

2021.06.14 16:41:37:745 | Debug | CoinEx     | [2] Sending POST signed request to https://api.coinex.com/v1/balance/coin/withdraw with request body {"access_id":"###","actual_amount":"0.00000001","coin_address":"bitcoincash:###","coin_type":"BCH","tonce":1623681697707,"transfer_method":"1"}
2021.06.14 16:41:38:006 | Debug | CoinEx     | [2] Response received in 259ms: {"code": 25, "data": {}, "message": "Signature error."}

**Comment by JKorf** [comment]
I have tested it, and for me it works when using BTC. The transfer_method has to be text, so not 0/1 but actually "onchain". I've pushed beta10 which has this text version again.
Make sure the following is correct:
1. You have Withdrawal rights on your API key
2. You have the withdrawal address whitelisted in your account

Also is it necessary for BCH to have the `bitcoincash:` prefix in the coin_address? Shouldn't it just be the address?

**Comment by tulasacra** [comment]
when i removed the "bitcoincash:" prefix i got:
 {"code": 310, "data": {}, "message": "Invalid withdrawal address"}
 
 but when i removed the prefix also from the whitelisted address it works
 thanks

**Comment by hadaeghimohsen** [comment]
Hi There
I downloading new version of Coinex but all Method show error "Method Not Found".
Can you help me?
thank you

**Comment by banegil** [comment]
Some help here please, I got this error trying to widthdrawal, already whitelisted and permissions:
{
	"code" : 25,
	"data" : {},
	"message" : "Signature Incorrect"
}

This is my code, works perfectly in other situation like send_order, but with withdrawal not, I don't know why:
        string url = "https://api.coinex.com/v1/balance/coin/withdraw";
        string action = "POST";	
        string ep = to_string (get_current_ms_epoch());
        string post_data = "{\"access_id\":\"" + api_key + "\",\"actual_amount\":\"1.00000000\",\"coin_address\":\"1KAv3pazbTk2JnQ5xTo6fpKK7p1it2RzD4\",\"coin_type\":\"BCH\",\"tonce\":" + ep + ",\"transfer_method\":\"onchain\"}";
        string msg = "access_id=" + api_key + "&actual_amount=1.00000000&coin_address=1KAv3pazbTk2JnQ5xTo6fpKK7p1it2RzD4&coin_type=BCH&tonce= " + ep + "&transfer_method=onchain&secret_key=" + api_secret;
        string signature = md5(msg);
        string_toupper(signature);
